### ISSUE TITLE
Грешка в мерната единица стр.7 от презентацията

### ISSUE THREAD

**Issue by tanya-evt** [BG-IT-Edu/School-Programming#10]
В презентацията на стр.7, трябва да е байт, вместо бит.

Courses/Software-Sciences/Module-2-DS-and-Algo/12.1-Data Structures-Overview-Basics/12.1-Data Structures-Overview-Basics.pptx

**Comment by alexmehandzhiyska** [comment]
Грешката е отстранена. Благодарим Ви!
