### ISSUE TITLE
Забележки по презентационния файл за сложност на алгоритмите 11-Algorithms-Intro-and-Complexity

### ISSUE THREAD

**Issue by zelenkroki** [BG-IT-Edu/School-Programming#11]
Привет,
Слайд 15 съдържа объркваща (според мене) информация за квадратната функция, описана като експоненциална?
Темп на растеж на функциите
O(n^2) означава, че функцията расте експоненциално, когато n нараства
Пример: ƒ(n)=n^2+2n+2

Дали може някой да го огледа и редактира?

С благодарност и поздрави.

**Comment by alexmehandzhiyska** [comment]
Здравейте, неточността е коригирана. Благодарим!
