### ISSUE TITLE
Проблем със събмитване на решения в Judge

### ISSUE THREAD

**Issue by tanya-evt** [BG-IT-Edu/School-Programming#8]
Има проблем със събмитване на решенията в Judge
Courses/Software-Sciences/Module-1-OOP/07.1-Classes-and-Objects-Basics/07.1-Classes-and-Objects-Basics-Exercises.docx
Грешка:
Compiled file is missing. Compiler output: MSBuild version 17.3.2+561848881 for .NET
  Determining projects to restore...
  Restored /tmp/ExecutionStrategies/eaby4lo0.i1m/NUnitLiteConsoleApp/NUnitLiteConsoleApp.csproj (in 709 ms).
/usr/share/dotnet/sdk/6.0.407/Microsoft.Common.CurrentVersion.targets(1220,5): error MSB3644: The reference assemblies for .NETFramework,Version=v4.7.2 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks [/tmp/ExecutionStrategies/eaby4lo0.i1m/UserProject/_01_ClassSquare.csproj]

**Comment by alexmehandzhiyska** [comment]
Здравейте! Причините да Ви излиза тази грешка в Judge са следните:

1. В решението Ви е използвана **стара версия на .NET** (4.7.2). Ако предадете решението в проект на **.NET Core 6**, този проблем ще бъде отстранен.

2. Класовете трябва да са **публични** (**public**), а не вътрешни (internal), за да може Judge да разчете решението.

3. При **архивиране** на файловете трябва да се включват **само solution файловете + csproj файла**. 

Ако промените тези три неща, решението Ви ще мине със **100/100 точки**.
