### ISSUE TITLE
Дреболия с изядена буква при методическите указания

### ISSUE THREAD

**Issue by zelenkroki** [BG-IT-Edu/School-Programming#9]
Всеки път се чудя как да не правя от мухата слон заради мултиплицирания цитат: „Всеки ученик трябва да напише по няколко практически задачи, защото програмиране с учи с практика.“

Вместо „Всеки ученик трябва да напише по няколко практически задачи, защото програмиране сЕ учи с практика.“

Съжалявам, не измислих по-дискретен начин да го докладвам това мъничко недогледано пропуснато „е“.

Поздрави.

**Comment by alexmehandzhiyska** [comment]
Здравейте! Благодарим Ви, че насочихте вниманието ни към този пропуск. Правописната грешка вече е отстранена. 

Поздрави!

**Comment by zelenkroki** [comment]
Сърдечно благодаря за реакцията и корекцията!
Поздрави!
